// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWfdDtfyvQFg0JDnAkibErV9uwfNxzks',
    appId: '1:50263862655:web:142e9b1a97793dbbde7e4a',
    messagingSenderId: '50263862655',
    projectId: 'noqueue-35cdf',
    authDomain: 'noqueue-35cdf.firebaseapp.com',
    databaseURL: 'https://noqueue-35cdf-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-35cdf.appspot.com',
    measurementId: 'G-CVCNWHPBWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4M5N_bF312fAqHXQtrFQ6JI0xUnOVAuk',
    appId: '1:50263862655:android:7dd74d98fc647638de7e4a',
    messagingSenderId: '50263862655',
    projectId: 'noqueue-35cdf',
    databaseURL: 'https://noqueue-35cdf-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-35cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mJq7472JNDwkFjAllWWsaRh0G97rgb0',
    appId: '1:50263862655:ios:ebf5986494e79d0bde7e4a',
    messagingSenderId: '50263862655',
    projectId: 'noqueue-35cdf',
    databaseURL: 'https://noqueue-35cdf-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-35cdf.appspot.com',
    androidClientId: '50263862655-6ogs27ujv9piolh8bkm8q3ariu06u92p.apps.googleusercontent.com',
    iosClientId: '50263862655-kcsf87m0hvtgobkjiu3n9q552pfcjgs6.apps.googleusercontent.com',
    iosBundleId: 'com.NoQ.noq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mJq7472JNDwkFjAllWWsaRh0G97rgb0',
    appId: '1:50263862655:ios:ebf5986494e79d0bde7e4a',
    messagingSenderId: '50263862655',
    projectId: 'noqueue-35cdf',
    databaseURL: 'https://noqueue-35cdf-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-35cdf.appspot.com',
    androidClientId: '50263862655-6ogs27ujv9piolh8bkm8q3ariu06u92p.apps.googleusercontent.com',
    iosClientId: '50263862655-kcsf87m0hvtgobkjiu3n9q552pfcjgs6.apps.googleusercontent.com',
    iosBundleId: 'com.NoQ.noq',
  );
}
